//! Embedded asset management.
//!
//! Assets (kernel, eBPF bytecode, guest agent) are optionally compiled into
//! the binary from `assets/`. On `nova setup` they are extracted to `/opt/nova/`.

use std::fs;
use std::io::{Read, Write};
use std::path::{Path, PathBuf};

// Generated by build.rs — constants for each embedded asset.
include!(concat!(env!("OUT_DIR"), "/embedded_assets.rs"));

/// Base directory for nova assets.
pub fn nova_dir() -> PathBuf {
    PathBuf::from("/opt/nova")
}

/// Info about one embeddable asset.
struct Asset {
    name: &'static str,
    data: &'static [u8],
    present: bool,
    dest: PathBuf,
    gzipped: bool,
}

fn asset_list() -> Vec<Asset> {
    let base = nova_dir();
    vec![
        Asset {
            name: "kernel",
            data: KERNEL_GZ,
            present: HAS_KERNEL_GZ,
            dest: base.join("vmlinux"),
            gzipped: true,
        },
        Asset {
            name: "agent",
            data: AGENT_GZ,
            present: HAS_AGENT_GZ,
            dest: base.join("bin/nova-eye-agent"),
            gzipped: true,
        },
        Asset {
            name: "ebpf/process",
            data: EBPF_PROCESS,
            present: HAS_EBPF_PROCESS,
            dest: base.join("ebpf/nova-eye-process"),
            gzipped: false,
        },
        Asset {
            name: "ebpf/network",
            data: EBPF_NETWORK,
            present: HAS_EBPF_NETWORK,
            dest: base.join("ebpf/nova-eye-network"),
            gzipped: false,
        },
        Asset {
            name: "ebpf/file",
            data: EBPF_FILE,
            present: HAS_EBPF_FILE,
            dest: base.join("ebpf/nova-eye-file"),
            gzipped: false,
        },
        Asset {
            name: "ebpf/http",
            data: EBPF_HTTP,
            present: HAS_EBPF_HTTP,
            dest: base.join("ebpf/nova-eye-http"),
            gzipped: false,
        },
        Asset {
            name: "ebpf/http-read",
            data: EBPF_HTTP_READ,
            present: HAS_EBPF_HTTP_READ,
            dest: base.join("ebpf/nova-eye-http-read"),
            gzipped: false,
        },
        Asset {
            name: "config",
            data: DEFAULT_CONFIG,
            present: HAS_DEFAULT_CONFIG,
            dest: PathBuf::from("/etc/nova/nova.toml"),
            gzipped: false,
        },
    ]
}

/// Returns true if any assets are embedded.
pub fn has_embedded_assets() -> bool {
    HAS_KERNEL_GZ || HAS_EBPF_PROCESS || HAS_AGENT_GZ || HAS_DEFAULT_CONFIG
}

/// List embedded assets and their status.
pub fn list_assets() {
    println!("Embedded assets:");
    for a in &asset_list() {
        let status = if a.present {
            format!("{} bytes", a.data.len())
        } else {
            "not bundled".to_string()
        };
        let exists = if a.dest.exists() { " (installed)" } else { "" };
        println!("  {:<18} {:>12}  → {}{}", a.name, status, a.dest.display(), exists);
    }
}

/// Extract all embedded assets to their destinations.
pub fn extract_all(force: bool) -> anyhow::Result<u32> {
    let mut count = 0u32;

    for asset in &asset_list() {
        if !asset.present {
            continue;
        }

        if asset.dest.exists() && !force {
            println!("  skip {} (already exists, use --force to overwrite)", asset.name);
            continue;
        }

        // Ensure parent directory exists.
        if let Some(parent) = asset.dest.parent() {
            fs::create_dir_all(parent)?;
        }

        if asset.gzipped {
            // Decompress gzip data.
            let mut decoder = flate2::read::GzDecoder::new(asset.data);
            let mut out = fs::File::create(&asset.dest)?;
            let mut buf = vec![0u8; 64 * 1024];
            loop {
                let n = decoder.read(&mut buf)?;
                if n == 0 {
                    break;
                }
                out.write_all(&buf[..n])?;
            }
        } else {
            fs::write(&asset.dest, asset.data)?;
        }

        // Make executables.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let is_executable = asset.name == "kernel"
                || asset.name == "agent"
                || asset.name.starts_with("ebpf/");
            if is_executable {
                fs::set_permissions(&asset.dest, fs::Permissions::from_mode(0o755))?;
            }
        }

        println!("  extracted {} → {}", asset.name, asset.dest.display());
        count += 1;
    }

    // Create runtime directories.
    for dir in &[
        "/run/nova",
        "/var/run/nova",
        "/var/lib/nova/images",
        "/var/lib/nova/policy/bundles",
    ] {
        let p = Path::new(dir);
        if !p.exists() {
            fs::create_dir_all(p)?;
            println!("  created {}", dir);
        }
    }

    Ok(count)
}

/// Generate a config pointing to extracted assets, if no config file exists.
pub fn generate_config_if_needed() -> Option<PathBuf> {
    let config_path = PathBuf::from("/etc/nova/nova.toml");
    if config_path.exists() {
        return Some(config_path);
    }

    // Check for embedded default config.
    if HAS_DEFAULT_CONFIG {
        if let Some(parent) = config_path.parent() {
            let _ = fs::create_dir_all(parent);
        }
        if fs::write(&config_path, DEFAULT_CONFIG).is_ok() {
            return Some(config_path);
        }
    }

    // Generate minimal config pointing to extracted kernel.
    let kernel_path = nova_dir().join("vmlinux");
    if kernel_path.exists() {
        let config = format!(
            r#"# Auto-generated by nova setup
[daemon]
socket = "/run/nova/nova.sock"
image_dir = "/var/lib/nova/images"
kernel = "{}"
api_port = 9800

[sensor]
events_log = "/var/run/nova/events.jsonl"
ebpf_dir = "/opt/nova/ebpf"

[sensor.guest]
enabled = false
agent_path = "/opt/nova/bin/nova-eye-agent"
event_port = 9876

[policy]
admission_enabled = true
enforcement_enabled = false
"#,
            kernel_path.display()
        );

        if let Some(parent) = config_path.parent() {
            let _ = fs::create_dir_all(parent);
        }
        if fs::write(&config_path, config).is_ok() {
            return Some(config_path);
        }
    }

    None
}
