//! Build script — detects embedded assets and generates `embedded_assets.rs`.

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let assets_dir = std::path::Path::new(&manifest_dir).join("assets");

    let mut code = String::from("// Auto-generated by build.rs — do not edit.\n\n");

    emit_asset(&mut code, "KERNEL_GZ", &assets_dir.join("vmlinux.gz"));
    emit_asset(&mut code, "AGENT_GZ", &assets_dir.join("nova-eye-agent.gz"));
    emit_asset(&mut code, "EBPF_PROCESS", &assets_dir.join("nova-eye-process"));
    emit_asset(&mut code, "EBPF_NETWORK", &assets_dir.join("nova-eye-network"));
    emit_asset(&mut code, "EBPF_FILE", &assets_dir.join("nova-eye-file"));
    emit_asset(&mut code, "EBPF_HTTP", &assets_dir.join("nova-eye-http"));
    emit_asset(
        &mut code,
        "EBPF_HTTP_READ",
        &assets_dir.join("nova-eye-http-read"),
    );
    emit_asset(
        &mut code,
        "DEFAULT_CONFIG",
        &assets_dir.join("default.toml"),
    );

    std::fs::write(
        std::path::Path::new(&out_dir).join("embedded_assets.rs"),
        code,
    )
    .unwrap();

    // Rerun if assets directory changes.
    println!("cargo:rerun-if-changed=assets/");
}

fn emit_asset(code: &mut String, name: &str, path: &std::path::Path) {
    if path.exists() {
        let abs = path
            .canonicalize()
            .unwrap()
            .display()
            .to_string()
            .replace('\\', "/");
        code.push_str(&format!(
            "pub const {name}: &[u8] = include_bytes!(\"{abs}\");\n"
        ));
        code.push_str(&format!("pub const HAS_{name}: bool = true;\n"));
    } else {
        code.push_str(&format!("pub const {name}: &[u8] = &[];\n"));
        code.push_str(&format!("pub const HAS_{name}: bool = false;\n"));
    }
}
